"""empty message

Revision ID: 39f7cabba3b2
Revises: 32695e01a756
Create Date: 2018-08-22 18:34:34.349778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f7cabba3b2'
down_revision = '32695e01a756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('term', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_courses_term'), 'courses', ['term'], unique=False)
    op.create_index(op.f('ix_courses_type_id'), 'courses', ['type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_type_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_term'), table_name='courses')
    op.drop_column('courses', 'term')
    # ### end Alembic commands ###
